/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.Docentes;

/**
 *
 * @author mrbingus
 */
public class FrmDocentePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmDocentePrincipal
     */
    public FrmDocentePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAsignatura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFechaClase = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTemaClas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnMarcarPresente = new javax.swing.JButton();
        btnMarcarAusencia = new javax.swing.JButton();
        btnMarcarJustificado = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(486, 512));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DOCENCIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setText("Asignatura designada:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblAsignatura.setText("ANALISIS MATEMATICO");
        jPanel2.add(lblAsignatura, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 260, 40));

        jLabel3.setText("REGISTRO DE ESTUDIANTES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Juan Armijos", "Lucas Becerra", "Pedro Carrion", "Javier Castillo", "Angelo Figueroa", "Enner  Hincapie", "Piero Hidalgo", "Luis Ortiz" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 330));

        jLabel4.setText("CLASE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel5.setText("Fecha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        lblFechaClase.setText("27-11-2023");
        jPanel1.add(lblFechaClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel7.setText("Tema");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        txtTemaClas.setText("Definicion de Limite");
        jPanel1.add(txtTemaClas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 280, 40));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Clase 27-11-2023", "Clase 28-11-2023", "Clase 30-11-2023", "Clase 01-12-2023", "Clase 04-12-2023", "Clase 05-12-2023", "Clase 06-12-2023", "Clase 08-12-2023" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 220, 190));

        jLabel6.setText("REGISTRO DE ASISTENCIA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btnMarcarPresente.setText("Presente");
        btnMarcarPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarPresenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnMarcarPresente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 90, -1));

        btnMarcarAusencia.setText("Ausente");
        jPanel1.add(btnMarcarAusencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 90, -1));

        btnMarcarJustificado.setText("Justificado");
        btnMarcarJustificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarJustificadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMarcarJustificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarcarPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarPresenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarPresenteActionPerformed

    private void btnMarcarJustificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarJustificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarJustificadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDocentePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDocentePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarcarAusencia;
    private javax.swing.JButton btnMarcarJustificado;
    private javax.swing.JButton btnMarcarPresente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblFechaClase;
    private javax.swing.JTextField txtTemaClas;
    // End of variables declaration//GEN-END:variables
}
